# Generated by Django 5.1 on 2024-08-23 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'カテゴリー'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='カテゴリー名'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='商品名')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='商品画像')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='商品価格')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='割引％')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='在庫量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.categories', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': '商品',
                'db_table': 'product',
            },
        ),
    ]
